---
title: "Creation of sampling location master lists"
author: "C. Mimeault"
date: "June 13, 2021"
output: pdf_document
---

```{r setup, include=FALSE}
# this code requires R version 4.1
remove(list=ls())
knitr::opts_chunk$set(echo = TRUE)

# the following line enables . => until enabled by default in R 4.2
Sys.setenv("_R_USE_PIPEBIND_" = "true") 
```

```{r libraries, include=FALSE}
library(tidyverse)
library(here)
library(janitor)
library(formattable)
library(stringdist)
library(knitr)
library(parzer)
```

This document complements the document in which data extracted from juvenile wild salmon sea lice monitoring in British Columbia (BC) reports (that can be found [here](https://mowi.com/caw/sustainability/wild-salmonid-lice-monitoring/)) were extracted from PDF to .csv format. This documents explains the steps to clean the datasets.

# Standardization of site numbers and names in dataset

```{r BA data, include=FALSE}
# read file and correct site names according to the master list
BA_data <- read_csv(here("data/interim/broughton_archipelago/broughton_archipelago_all_data.csv")) |>
  clean_names() |>
  mutate(site_name = replace(site_name, site_name == "Denham Is", "Denham Island"),
         site_name = replace(site_name, site_name == "Doctor Island Fish \nFarm", "Doctor Island Fish Farm"),
         site_name = replace(site_name, site_name == "Doctor Island FF", "Doctor Island Fish Farm"),
         site_name = replace(site_name, site_name == "Glacier Falls FF", "Glacier Falls Fish Farm"),
         site_name = replace(site_name, site_name == "Glacier Falls Fish \nFarm", "Glacier Falls Fish Farm"),
         site_name = replace(site_name, site_name == "Hanson", "Hanson Island"),
         site_name = replace(site_name, site_name == "Humphrey Rock \nFish Farm", "Humphrey Rock"),
         site_name = replace(site_name, site_name == "Kwatsi Bay", "Kwatsi Point"),
         site_name = replace(site_name, site_name == "Matsui Bay", "Matsiu Bay"),   
         site_name = replace(site_name, site_name == "Midsummer Island Fish \nFarm", "Midsummer Island Fish Farm (Potts Bay)"), 
         site_name = replace(site_name, site_name == "Midsummer Island \nFish Farm", "Midsummer Island Fish Farm (Potts Bay)"),  
         site_name = replace(site_name, site_name == "Penphase Pass", "Penphrase Passage"),
         site_name = replace(site_name, site_name == "Penphrase Pass", "Penphrase Passage"),
         site_name = replace(site_name, site_name == "Sargeaunt Pass", "Sargeaunt Pass Fish Farm"),
         site_name = replace(site_name, site_name == "Sargeaunt Pass \nFish Farm", "Sargeaunt Pass Fish Farm"),
         site_name = replace(site_name, site_name == "Wakeman 5", "Wakeman 3"),
         site_name = replace(site_name, site_name == "Wehlis Bay FF", "Wehlis Bay Fish Farm"),
         site_name = replace(site_name, site_name == "Wehlis Bay Fish \nFarm", "Wehlis Bay Fish Farm")
         )
```

```{r BA data include all site names, include=FALSE}
# cleaning up the site numbers according to the master list, for example replace the "Site 01" with "1"
BA_data <- BA_data |>
  mutate(site_number = replace(site_number, site_number == "Site 1", "1"),
         site_number = replace(site_number, site_number == "Site 2", "2"),
         site_number = replace(site_number, site_number == "Site 3", "3"),
         site_number = replace(site_number, site_number == "Site 4", "4"),
         site_number = replace(site_number, site_number == "Site 04", "4"),
         site_number = replace(site_number, site_number == "Site 5", "5"),
         site_number = replace(site_number, site_number == "Site 05", "5"),
         site_number = replace(site_number, site_number == "Site 06", "6"),
         site_number = replace(site_number, site_number == "Site 7", "7"),
         site_number = replace(site_number, site_number == "Site 07", "7"),
         site_number = replace(site_number, site_number == "Site 8", "8"),
         site_number = replace(site_number, site_number == "Site 08", "8"),
         site_number = replace(site_number, site_number == "Site 9", "9"),
         site_number = replace(site_number, site_number == "Site 09", "9"),
         site_number = replace(site_number, site_number == "Site 10", "10"),
         site_number = replace(site_number, site_number == "Site 11", "11"),
         site_number = replace(site_number, site_number == "Site 12", "12"),
         site_number = replace(site_number, site_number == "Site 13", "13"),
         site_number = replace(site_number, site_number == "Site 14", "14"),
         site_number = replace(site_number, site_number == "Site 15", "15"),
         site_number = replace(site_number, site_number == "Site 16", "16"),
         site_number = replace(site_number, site_number == "Site 17", "17"),
         site_number = replace(site_number, site_number == "Site 18", "18"),
         site_number = replace(site_number, site_number == "Site 19", "19"),
         site_number = replace(site_number, site_number == "Site 20", "20"),
         site_number = replace(site_number, site_number == "Site 21", "21"),
         site_number = replace(site_number, site_number == "Site 22", "22"),
         site_number = replace(site_number, site_number == "Site A", "A"),
         site_number = replace(site_number, site_number == "Site B", "B"),
         site_number = replace(site_number, site_number == "Site C", "C"),
         site_number = replace(site_number, site_number == "Site D", "D"),
         site_number = replace(site_number, site_number == "Site E", "E"),
         site_number = replace(site_number, site_number == "Site F", "F"),
         site_number = replace(site_number, site_number == "Site G", "G"),
         site_number = replace(site_number, site_number == "Site H", "H"),
         site_number = replace(site_number, site_number == "Site I", "I"),
         site_number = replace(site_number, site_number == "Site J", "J")
         )
```

```{r}
aaa <- BA_data |>
  mutate(
    site_name =  if_else(site_number == "1", "Swanson Island Fish Farm", site_name),
    site_name =  if_else(site_number == "2", "Midsummer Island Fish Farm (Potts Bay)", site_name),
    site_name =  if_else(site_number == "3", "Chop Bay", site_name),
    site_name =  if_else(site_number == "4", "Lady Island", site_name),
    site_name =  if_else(site_number == "5", "Doctor Island Fish Farm", site_name),
    site_name =  if_else(site_number == "6", "Brent Bay", site_name),
    site_name =  if_else(site_number == "7", "Shelterless Bay", site_name),
    site_name =  if_else(site_number == "8", "Lance Bay", site_name),
    site_name =  if_else(site_number == "9", "Sargeaunt Pass Fish Farm", site_name),
    site_name =  if_else(site_number == "10", "Humphrey Rock", site_name),
    site_name =  if_else(site_number == "11", "Pumish Point", site_name),
    site_name =  if_else(site_number == "12", "Oline Point", site_name),
    site_name =  if_else(site_number == "13", "London Point", site_name),
    site_name =  if_else(site_number == "14", "Miller Point", site_name),
    site_name =  if_else(site_number == "15", "Kwatsi Point", site_name),
    site_name =  if_else(site_number == "16", "Glacier Falls Fish Farm", site_name),
    site_name =  if_else(site_number == "17", "Viner Sound", site_name),
    site_name =  if_else(site_number == "18", "Denham Island", site_name),
    site_name =  if_else(site_number == "19", "Baker Island", site_name),
    site_name =  if_else(site_number == "20", "Jumper Island", site_name),
    site_name =  if_else(site_number == "21", "Arthur Point", site_name),
    site_name =  if_else(site_number == "22", "Wicklow Point", site_name),
    site_name =  if_else(site_number == "A", "Bennett Point Fish Farm (Noo-La)", site_name),
    site_name =  if_else(site_number == "B", "Sambo Point", site_name),
    site_name =  if_else(site_number == "C", "Penphrase Passage", site_name),
    site_name =  if_else(site_number == "D", "Harry Bay", site_name),
    site_name =  if_else(site_number == "E", "Phillip Point West", site_name),
    site_name =  if_else(site_number == "F", "Sutlej North", site_name),
    site_name =  if_else(site_number == "G", "Codrington Point", site_name),
    site_name =  if_else(site_number == "H", "Wehlis Bay Fish Farm", site_name),
    site_name =  if_else(site_number == "I", "Alder Bay", site_name),
    site_name =  if_else(site_number == "J", "Poppelwell Point", site_name),
    site_name =  if_else(site_number == "1000", "Batt Bluff West", site_name),
    site_name =  if_else(site_number == "1001", "Freshwater Bay", site_name),
    site_name =  if_else(site_number == "1002", "Gwayasdums 1", site_name),
    site_name =  if_else(site_number == "1003", "Hanson Island", site_name),
    site_name =  if_else(site_number == "1004", "Hoeya Sound", site_name),
    site_name =  if_else(site_number == "1005", "Kokish Estuary", site_name),
    site_name =  if_else(site_number == "1006", "Larsen Island Fish Farm", site_name),
    site_name =  if_else(site_number == "1007", "Matsiu Bay", site_name),
    site_name =  if_else(site_number == "1008", "McKenzie Cove", site_name),
    site_name =  if_else(site_number == "1009", "Mount Frederick Bay", site_name),
    site_name =  if_else(site_number == "1010", "Nimpkish Estuary", site_name),    
    site_name =  if_else(site_number == "1011", "Tomakstum Island", site_name),    
    site_name =  if_else(site_number == "1012", "Hoeya South", site_name),    
    site_name =  if_else(site_number == "1013", "Wakeman 3", site_name),
    site_name =  if_else(site_number == "1014", "Wakeman 4", site_name)
  )
```

```{r, BA data complete missing site numbers based on site names, include=FALSE}
test <- BA_data |>
  mutate(
    site_number =  if_else(site_name == "Alder Bay", "I", site_number),
    site_number =  if_else(site_name == "Arthur Point", "21", site_number),
    site_number = if_else(site_name == "Baker Island", "19", site_number),
    site_number =  if_else(site_name == "Batt Bluff West", "1000", site_number),
    site_number =  if_else(site_name == "Bennett Point Fish Farm (Noo-La)", "A", site_number),
    site_number = if_else(site_name == "Brent Bay", "6", site_number),
    site_number =  if_else(site_name == "Chop Bay", "3", site_number),
    site_number =  if_else(site_name == "Codrington Point", "G", site_number),
    site_number = if_else(site_name == "Denham Island", "18", site_number),
    site_number =  if_else(site_name == "Doctor Island Fish Farm", "5", site_number),
    site_number =  if_else(site_name == "Freshwater Bay", "1001", site_number),
    site_number = if_else(site_name == "Glacier Falls Fish Farm", "16", site_number),
    site_number =  if_else(site_name == "Gwayasdums 1", "1002", site_number),
    site_number =  if_else(site_name == "Hanson Island", "1008", site_number),
    site_number = if_else(site_name == "Harry Bay", "D", site_number),
    site_number =  if_else(site_name == "Hoeya Sound", "1004", site_number),
    site_number =  if_else(site_name == "Hoeya South", "1013", site_number),
    site_number = if_else(site_name == "Humphrey Rock", "10", site_number),
    site_number =  if_else(site_name == "Kokish Estuary", "1005", site_number),
    site_number =  if_else(site_name == "Kwatsi Point", "15", site_number),
    site_number = if_else(site_name == "Lady Island", "4", site_number),
    site_number =  if_else(site_name == "Lance Bay", "8", site_number),
    site_number =  if_else(site_name == "Larsen Island Fish Farm", "1006", site_number),
    site_number = if_else(site_name == "London Point", "13", site_number),
    site_number =  if_else(site_name == "Matsiu Bay", "1007", site_number),
    site_number =  if_else(site_name == "McKenzie Cove", "1009", site_number),
    site_number = if_else(site_name == "Midsummer Island Fish Farm (Potts Bay)", "2", site_number),
    site_number =  if_else(site_name == "Miller Point", "14", site_number),
    site_number =  if_else(site_name == "Mount Frederick Bay", "1010", site_number),
    site_number = if_else(site_name == "Nimpkish Estuary", "1011", site_number),
    site_number =  if_else(site_name == "Oline Point", "12", site_number),
    site_number =  if_else(site_name == "Penphrase Passage", "C", site_number),
    site_number = if_else(site_name == "Phillip Point West", "E", site_number),
    site_number =  if_else(site_name == "Poppelwell Point", "J", site_number),
    site_number =  if_else(site_name == "Pumish Point", "11", site_number),
    site_number = if_else(site_name == "Sambo Point", "B", site_number),
    site_number =  if_else(site_name == "Sargeaunt Pass Fish Farm", "9", site_number),
    site_number =  if_else(site_name == "Shelterless Bay", "7", site_number),
    site_number = if_else(site_name == "Sutlej North", "F", site_number),
    site_number =  if_else(site_name == "Swanson Island Fish Farm", "1", site_number),
    site_number =  if_else(site_name == "Tomakstum Island", "1012", site_number),
    site_number = if_else(site_name == "Viner Sound", "17", site_number),
    site_number =  if_else(site_name == "Wakeman 3", "1014", site_number),
    site_number =  if_else(site_name == "Wakeman 4", "1015", site_number),
    site_number = if_else(site_name == "Wehlis Bay Fish Farm", "H", site_number),
    site_number =  if_else(site_name == "Wicklow Point", "22", site_number)
  )
```

https://stackoverflow.com/questions/17013227/select-only-rows-if-its-value-in-a-particular-column-is-na-in-r

