---
title: "Creation of master sampling location lists"
author: "C. Mimeault"
date: "June 13, 2021"
output: pdf_document
---

```{r setup, include=FALSE}
# this code requires R version 4.1
remove(list=ls())
knitr::opts_chunk$set(echo = TRUE)

# the following line enables . => until enabled by default in R 4.2
Sys.setenv("_R_USE_PIPEBIND_" = "true") 
```

```{r libraries, include=FALSE}
library(tidyverse)
library(here)
library(janitor)
library(formattable)
library(stringdist)
library(knitr)
library(parzer)
```

This document complements the document in which data extracted from juvenile wild salmon sea lice monitoring in British Columbia (BC) reports (that can be found [here](https://mowi.com/caw/sustainability/wild-salmonid-lice-monitoring/)) were extracted from PDF to .csv format. 

There are three main regions:

* Broughton Archipelago
* Discovery Islands
* Quatsino

# Standardization of sampling locations

## Broughton Archipelago

```{r BA data, include=FALSE}
BA_data <- read_csv(here("data/interim/broughton_archipelago/broughton_archipelago_all_data.csv")) %>% 
  clean_names()
```

```{r BA locations, include=FALSE}
locations_BA_2016 <- read_csv(here("data/interim/broughton_archipelago/all_broughton_archipelago_locations_2016.csv")) |> 
  clean_names()

locations_BA_2017 <- read_csv(here("data/interim/broughton_archipelago/all_broughton_archipelago_locations_2017.csv")) |> 
  clean_names()

locations_BA_2018 <- read_csv(here("data/interim/broughton_archipelago/all_broughton_archipelago_locations_2018.csv")) |> 
  clean_names()

locations_BA_2019 <- read_csv(here("data/interim/broughton_archipelago/all_broughton_archipelago_locations_2019.csv")) |> 
  clean_names()

locations_BA_2020 <- read_csv(here("data/interim/broughton_archipelago/all_broughton_archipelago_locations_2020.csv")) |> 
  clean_names()

BA_locations <- bind_rows(locations_BA_2016, locations_BA_2017, locations_BA_2018, locations_BA_2019, locations_BA_2020)
```

```{r BA locations master list lat long, include=FALSE}
# the GPS coordinates are in an incomplete (missing negative sign in longitudes) degrees and decimal minutes (DD:MM.MM) format
# provided as character strings
# converting the provided latitudes and longitudes to the decimal degrees (DD.DD) format with the parzer package
BA_locations <- BA_locations |>
  mutate(
    lat_decimal_degrees = parse_lat(latitude),
    long_decimal_degrees = parse_lon(paste(longitude, "W"))
  )
```

```{r BA locations master list names, include=FALSE}
# re-conciliating similar names and different GPS coordinates collected at the same location
# note that the coordinates for Sambo Point refer to a location on land which seems to be an error
# no fish sampled or collected at Sambo Point so leaving it in without correction
# GPS location of Wakeman 5 in 2019 is not on the map which only locates Wakeman 3 and 4
# Wakeman 5 was assumed to be the same as Wakeman 3
BA_locations <- BA_locations |>
  mutate(site_number = as_factor(site_number),
         site_name = replace(site_name, site_name == "Alder Point", "Alder Bay"),
         site_name = replace(site_name, site_name == "Hanson", "Hanson Island"),
         site_name = replace(site_name, site_name == "Humphrey Rock Fish Farm", "Humphrey Rock"),
         site_name = replace(site_name, site_name == "Kwatsi Bay", "Kwatsi Point"),         
         site_name = replace(site_name, site_name == "Mount Frederick", "Mount Frederick Bay"),
         site_name = replace(site_name, site_name == "Sargeaunt Pass", "Sargeaunt Pass Fish Farm"),
         site_name = replace(site_name, site_name == "Penphrase Pass", "Penphrase Passage"),
         site_name = replace(site_name, site_name == "Wakeman 5", "Wakeman 3"),
         site_name = replace(site_name, site_name == "Wicklow Bay", "Wicklow Point")
         ) |>
  distinct()
```

```{r BA locations master list unique records, include=FALSE}
# new locations added in 2019 and 2020 reports
# re-conciliating GPS coordinates collected at the same location 
# error in Hoeya South GPS coordinates in 2019 report - using GPS coordinates from 2020 report
# helpful website to locate several sites: https://www.mapcustomizer.com/
# GPS coordinates for Millar Point were approximately 500m apart - assumed to be the same location


BA_clean_locations <- BA_locations |>
  filter(
    (site_name == "Alder Bay" & site_number == "I") |
    (site_name == "Arthur Point" & site_number == "21") |
    (site_name == "Baker Island" & site_number == "19") |
    (site_name == "Batt Bluff West") |
    (site_name == "Bennett Point Fish Farm (Noo-La)") |
    (site_name == "Brent Bay" & site_number == "6") |
    (site_name == "Chop Bay" & site_number == "3") |
    (site_name == "Codrington Point" & site_number == "G") |
    (site_name == "Denham Island" & site_number == "18") |
    (site_name == "Doctor Island Fish Farm" & site_number == "5") |
    (site_name == "Freshwater Bay") |
    (site_name == "Glacier Falls Fish Farm" & site_number == "16") |
    (site_name == "Gwayasdums 1") |
    (site_name == "Hanson Island") |
    (site_name == "Harry Bay" & site_number == "D") |
    (site_name == "Hoeya Sound") | 
    (site_name == "Hoeya South" & long_decimal_degrees == "-125.9812") |
    (site_name == "Humphrey Rock" & site_number == "10") |
    (site_name == "Jumper Island" & site_number == "20") |
    (site_name == "Kokish Estuary") |
    (site_name == "Kwatsi Point" & site_number == "15") |
    (site_name == "Lady Island" & site_number == "4") |
    (site_name == "Lance Bay" & site_number == "8") |
    (site_name == "Larsen Island Fish Farm") |
    (site_name == "London Point" & site_number == "13") |
    (site_name == "Matsiu Bay") |
    (site_name == "McKenzie Cove") |
    (site_name == "Midsummer Island Fish Farm (Potts Bay)" & site_number == "2") |
    (site_name == "Miller Point" & site_number == "14") |
    (site_name == "Mount Frederick Bay") |
    (site_name == "Nimpkish Estuary") |
    (site_name == "Oline Point" & site_number == "12") |
    (site_name == "Penphrase Passage" & site_number == "C") |
    (site_name == "Phillip Point West" & site_number == "E") |
    (site_name == "Poppelwell Point" & site_number == "J") |
    (site_name == "Pumish Point" & site_number == "11") |
    (site_name == "Sambo Point") |
    (site_name == "Sargeaunt Pass Fish Farm" & site_number == "9") |
    (site_name == "Shelterless Bay" & site_number == "7") |
    (site_name == "Sutlej North" & site_number == "F") |
    (site_name == "Swanson Island Fish Farm" & site_number == "1") |
    (site_name == "Tomakstum Island") |
    (site_name == "Viner Sound" & site_number == "17") |
    (site_name == "Wakeman" & site_number == "") |
    (site_name == "Wakeman 3" & long_decimal_degrees == "-126.5154") |
    (site_name == "Wakeman 4" & long_decimal_degrees == "-126.4886") |
    (site_name == "Wehlis Bay Fish Farm" & site_number == "H") |
    (site_name == "Wicklow Point" & site_number == "22")
      ) |>
  select(site_number, site_name, lat_decimal_degrees, long_decimal_degrees)
```
